hamnadmin/hamnadmin/register/urls.py
from django.urls import re_path

import hamnadmin.register.views
import hamnadmin.auth

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    re_path(r'^$', hamnadmin.register.views.root),
    re_path(r'^new/$', hamnadmin.register.views.edit),
    re_path(r'^edit/(?P<id>\d+)/$', hamnadmin.register.views.edit),
    re_path(r'^delete/(?P<id>\d+)/$', hamnadmin.register.views.delete),
    re_path(r'^archive/(?P<id>\d+)/$', hamnadmin.register.views.archive),
    re_path(r'^teamremove/(?P<teamid>\d+)/(?P<blogid>\d+)/$', hamnadmin.register.views.remove_from_team),

    re_path(r'^blogposts/(\d+)/hide/(\d+)/$', hamnadmin.register.views.blogpost_hide),
    re_path(r'^blogposts/(\d+)/unhide/(\d+)/$', hamnadmin.register.views.blogpost_unhide),
    re_path(r'^blogposts/(\d+)/delete/(\d+)/$', hamnadmin.register.views.blogpost_delete),

    re_path(r'^moderate/$', hamnadmin.register.views.moderate),
    re_path(r'^moderate/reject/(\d+)/$', hamnadmin.register.views.moderate_reject),
    re_path(r'^moderate/approve/(\d+)/$', hamnadmin.register.views.moderate_approve),
    re_path(r'^login/$', hamnadmin.auth.login),
    re_path(r'^auth_receive/$', hamnadmin.auth.auth_receive),
    re_path(r'^auth_api/$', hamnadmin.auth.auth_api),
    re_path(r'^logout/$', hamnadmin.auth.logout),

    re_path(r'^admin/', admin.site.urls),
]

hamnadmin/hamnadmin/urls.py
from django.urls import re_path, include

import hamnadmin.register.views
from hamnadmin.register.feeds import PostFeed

urlpatterns = [
    re_path(r'^$', hamnadmin.register.views.planet_home),
    re_path(r'^add.html$', hamnadmin.register.views.planet_add),
    re_path(r'^feeds.html$', hamnadmin.register.views.planet_feeds),

    re_path(r'^rss20(?P<type>_short)?\.xml$', PostFeed()),
    re_path(r'^register/', include('hamnadmin.register.urls')),
]

hamnadmin/hamnadmin/register/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime, timedelta

from hamnadmin.util.shortlink import urlvalmap


class Team(models.Model):
    teamurl = models.CharField(max_length=255, blank=False)
    name = models.CharField(max_length=255, blank=False)
    manager = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return "%s (%s)" % (self.name, self.teamurl)

    class Meta:
        db_table = 'teams'
        ordering = ['name', ]

    class Admin:
        pass

    @property
    def all_blogs(self):
        return self.blog_set.filter(approved=True, archived=False)


class Blog(models.Model):
    feedurl = models.CharField(max_length=255, blank=False)
    name = models.CharField(max_length=255, blank=False)
    blogurl = models.CharField(max_length=255, blank=False)
    lastget = models.DateTimeField(default=datetime(2000, 1, 1))
    lastsuccess = models.DateTimeField(null=True, blank=True)
    user = models.ForeignKey(User, null=False, blank=False, on_delete=models.CASCADE)
    approved = models.BooleanField(default=False)
    archived = models.BooleanField(default=False)
    authorfilter = models.CharField(max_length=255, default='', blank=True)
    team = models.ForeignKey(Team, db_column='team', blank=True, null=True, on_delete=models.CASCADE)
    twitteruser = models.CharField(max_length=255, default='', blank=True)
    excludestats = models.BooleanField(null=False, blank=False, default=False)

    # Things that may change
    new_blogurl = None

    def __str__(self):
        return "%s (%s)" % (self.name, self.feedurl)

    @property
    def email(self):
        return self.user.email

    @property
    def latestentry(self):
        try:
            return self.posts.filter(hidden=False)[0]
        except Exception:
            return None

    @property
    def recent_entries(self):
        return self.posts.order_by('-dat')[:10]

    class Meta:
        db_table = 'feeds'
        ordering = ['approved', 'name']

    class Admin:
        pass


class Post(models.Model):
    feed = models.ForeignKey(Blog, db_column='feed', related_name='posts', on_delete=models.CASCADE)
    guid = models.CharField(max_length=255)
    link = models.CharField(max_length=255)
    txt = models.TextField()
    dat = models.DateTimeField()
    title = models.CharField(max_length=255)
    guidisperma = models.BooleanField(default=False)
    hidden = models.BooleanField(default=False)
    twittered = models.BooleanField(default=False)
    shortlink = models.CharField(max_length=255)

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'posts'
        ordering = ['-dat']
        unique_together = [
            ('id', 'guid'),
        ]

    class Admin:
        pass

    def update_shortlink(self):
        self.shortlink = self._get_shortlink()
        self.save(update_fields=['shortlink'])

    def _get_shortlink(self):
        s = ""
        i = self.id
        while i > 0:
            s = urlvalmap[i % 64] + s
            i //= 64
        return "https://postgr.es/p/%s" % s


class AuditEntry(models.Model):
    logtime = models.DateTimeField(default=datetime.now)
    user = models.CharField(max_length=32)
    logtxt = models.CharField(max_length=1024)

    def __init__(self, username, txt):
        super(AuditEntry, self).__init__()
        self.user = username
        self.logtxt = txt

    def __str__(self):
        return "%s (%s): %s" % (self.logtime, self.user, self.logtxt)

    class Meta:
        db_table = 'auditlog'
        ordering = ['logtime']


class AggregatorLog(models.Model):
    ts = models.DateTimeField(auto_now=True)
    feed = models.ForeignKey(Blog, db_column='feed', on_delete=models.CASCADE)
    success = models.BooleanField()
    info = models.TextField()

    class Meta:
        db_table = 'aggregatorlog'
        ordering = ['-ts']

    def __str__(self):
        return "Log entry for %s (%s)" % (self.feed.name, self.ts)


class ModeratorNotes(models.Model):
    ts = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, null=False, blank=False, on_delete=models.CASCADE)
    feed = models.ForeignKey(Blog, null=False, blank=False, db_column='feed', on_delete=models.CASCADE)
    note = models.TextField()

    class Meta:
        db_table = 'moderatornotes'
        verbose_name_plural = 'Moderator notes'
        ordering = ['ts']

    def __str__(self):
        return "Note for %s by %s at %s" % (self.feed.name, self.user, self.ts)

hamnadmin/hamnadmin/register/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required, user_passes_test
from django.conf import settings
from django.db import transaction
from django.db.models import Count, Max, Q, Subquery, OuterRef, Exists, FilteredRelation
from django.contrib import messages

from hamnadmin.register.models import Post, Blog, Team, AggregatorLog, AuditEntry, ModeratorNotes
from hamnadmin.mailqueue.util import send_simple_mail
from hamnadmin.util.varnish import purge_url, purge_xkey, purge_root_and_feeds

import datetime

from .forms import BlogEditForm, ModerateRejectForm


# Public planet
def planet_home(request):
    statdate = datetime.datetime.now() - datetime.timedelta(days=61)
    posts = Post.objects.select_related('feed', 'feed__team').filter(hidden=False, feed__approved=True).order_by('-dat')[:30]
    topposters = Blog.objects.filter(approved=True, excludestats=False, posts__hidden=False, posts__dat__gt=statdate).annotate(numposts=Count('posts__id')).order_by('-numposts')[:10]
    topteams = Team.objects.filter(blog__approved=True, blog__excludestats=False, blog__posts__hidden=False, blog__posts__dat__gt=statdate).annotate(numposts=Count('blog__posts__id')).order_by('-numposts')[:10]
    return render(request, 'index.tmpl', {
        'posts': posts,
        'topposters': topposters,
        'topteams': topteams,
    })


def planet_feeds(request):
    return render(request, 'feeds.tmpl', {
        'feeds': Blog.objects.filter(approved=True, archived=False),
        'teams': Team.objects.filter(blog__approved=True).distinct().order_by('name'),
    })


def planet_add(request):
    return render(request, 'add.tmpl', {
    })


# Registration interface (login and all)
def issuperuser(user):
    return user.is_authenticated and user.is_superuser


@login_required
def root(request):
    isadmin = request.user.is_superuser and 'admin' in request.GET and request.GET['admin'] == '1'
    if isadmin:
        blogs = Blog.objects.select_related('user').all()
    else:
        blogs = Blog.objects.filter(user=request.user)

    blogs = blogs.annotate(
        has_entries=Exists(Post.objects.filter(feed=OuterRef("pk"), hidden=False)),
        recent_failure_entries=FilteredRelation('aggregatorlog', condition=Q(aggregatorlog__success=False, aggregatorlog__ts__gt=datetime.datetime.now() - datetime.timedelta(days=1))),
        last_was_success=Subquery(AggregatorLog.objects.filter(feed=OuterRef("pk")).values('success')[:1]),
    ).annotate(
        recent_failures=Count('recent_failure_entries'),
    ).order_by('archived', 'approved', 'name')

    return render(request, 'index.html', {
        'blogs': blogs,
        'teams': Team.objects.filter(manager=request.user).prefetch_related('blog_set').order_by('name'),
        'title': 'All blogs' if isadmin else 'Your blogs',
        'isadmin': isadmin,
    })


@login_required
@transaction.atomic
def edit(request, id=None):
    if id:
        blogqs = Blog.objects.all().annotate(
            has_entries=Exists(Post.objects.filter(feed=OuterRef("pk"), hidden=False)),
            recent_failure_entries=FilteredRelation('aggregatorlog', condition=Q(aggregatorlog__success=False, aggregatorlog__ts__gt=datetime.datetime.now() - datetime.timedelta(days=1))),
        ).annotate(
            recent_failures=Count('recent_failure_entries'),
        )
        if request.user.is_superuser:
            blog = get_object_or_404(blogqs, id=id)
        else:
            blog = get_object_or_404(blogqs, id=id, user=request.user)
    else:
        blog = Blog(user=request.user, name="{0} {1}".format(request.user.first_name, request.user.last_name))

    if request.method == 'POST':
        if 'note' in request.POST:
            form = BlogEditForm(request, instance=blog)
            note = ModeratorNotes(feed=blog, note=request.POST['note'], user=request.user)
            note.save()
            return HttpResponseRedirect("/register/edit/{0}/".format(blog.id))
        else:
            saved_url = blog.feedurl
            saved_filter = blog.authorfilter
            saved_team = blog.team
            form = BlogEditForm(request, data=request.POST, instance=blog)
            if form.is_valid():
                if id:
                    # This is an existing one. If we change the URL of the blog, it needs to be
                    # de-moderated if it was previously approved.
                    if blog.approved:
                        if saved_url != form.cleaned_data['feedurl'] or saved_filter != form.cleaned_data['authorfilter']:
                            obj = form.save()
                            obj.approved = False
                            obj.save(update_fields=['approved'])

                            send_simple_mail(
                                settings.EMAIL_SENDER,
                                settings.NOTIFICATION_RECEIVER,
                                "A blog was edited on Planet PostgreSQL",
                                "The blog at {0}\nwas edited by {1} in a way that needs new moderation.\n\nTo moderate: https://planet.postgresql.org/register/moderate/\n\n".format(blog.feedurl, blog.user),
                                sendername="Planet PostgreSQL",
                                receivername="Planet PostgreSQL Moderators",
                            )

                            messages.warning(request, "Blog has been resubmitted for moderation, and is temporarily disabled.")

                            purge_root_and_feeds()
                            purge_url('/feeds.html')

                            return HttpResponseRedirect("/register/edit/{0}/".format(obj.id))

                obj = form.save()

                if obj.team and obj.team != saved_team:
                    # We allow anybody to join a team by default, and will just send a notice
                    # so the team manager can undo it.
                    send_simple_mail(settings.EMAIL_SENDER,
                                     obj.team.manager.email,
                                     "A blog joined your team on Planet PostgreSQL",
                                     "The blog at {0} by {1} {2}\nhas been added to your team {3} on Planet PostgreSQL\n\nIf this is correct, you do not need to do anything.\n\nIf this is incorrect, please go to\n\nhttps://planet.postgresql.org/register/\n\nand click the button to remove the blog from your team.\nWe apologize if this causes work for you.\n\n".format(
                                         obj.feedurl,
                                         obj.user.first_name, obj.user.last_name,
                                         obj.team.name),
                                     sendername="Planet PostgreSQL",
                                     receivername="{0} {1}".format(obj.team.manager.first_name, obj.team.manager.last_name),
                                     )

                return HttpResponseRedirect("/register/edit/{0}/".format(obj.id))
    else:
        form = BlogEditForm(request, instance=blog)

    return render(request, 'edit.html', {
        'new': id is None,
        'form': form,
        'blog': blog,
        'log': AggregatorLog.objects.filter(feed=blog).order_by('-ts')[:30],
        'notes': ModeratorNotes.objects.filter(feed=blog).order_by('ts'),
        'posts': Post.objects.filter(feed=blog).order_by('-dat')[:10],
        'title': 'Edit blog: %s' % blog.name,
    })


@login_required
@transaction.atomic
def delete(request, id):
    if request.user.is_superuser:
        blog = get_object_or_404(Blog, id=id)
    else:
        blog = get_object_or_404(Blog, id=id, user=request.user)

    send_simple_mail(
        settings.EMAIL_SENDER,
        settings.NOTIFICATION_RECEIVER,
        "A blog was deleted on Planet PostgreSQL",
        "The blog at {0} by {1}\nwas deleted by {2}\n\n".format(blog.feedurl, blog.name, request.user.username),
        sendername="Planet PostgreSQL",
        receivername="Planet PostgreSQL Moderators",
    )
    blog.delete()
    messages.info(request, "Blog deleted.")
    purge_root_and_feeds()
    purge_url('/feeds.html')
    return HttpResponseRedirect("/register/")


@login_required
@transaction.atomic
def archive(request, id):
    if request.user.is_superuser:
        blog = get_object_or_404(Blog, id=id)
    else:
        blog = get_object_or_404(Blog, id=id, user=request.user)

    send_simple_mail(
        settings.EMAIL_SENDER,
        settings.NOTIFICATION_RECEIVER,
        "A blog was archived on Planet PostgreSQL",
        "The blog at {0} by {1}\nwas archived by {2}\n\n".format(blog.feedurl, blog.name, request.user.username),
        sendername="Planet PostgreSQL",
        receivername="Planet PostgreSQL Moderators",
    )
    blog.archived = True
    blog.save(update_fields=['archived'])
    messages.info(request, "Blog archived.")
    return HttpResponseRedirect("/register/")


@login_required
@transaction.atomic
def remove_from_team(request, teamid, blogid):
    team = get_object_or_404(Team, id=teamid, manager=request.user)
    blog = get_object_or_404(Blog, id=blogid)

    if blog.team != team:
        messages.error(request, "The blog at {0} does not (any more?) belong to the team {1}!".format(
            blog.feedurl,
            team.name))
        return HttpResponseRedirect("/register/")

    blog.team = None
    blog.save(update_fields=['team'])

    send_simple_mail(settings.EMAIL_SENDER,
                     settings.NOTIFICATION_RECEIVER,
                     "A blog was removed from a team on Planet PostgreSQL",
                     "The blog at {0} by {1} {2}\nwas removed from team {3} by {4}.\n".format(
                         blog.feedurl, blog.user.first_name, blog.user.last_name, team.name, request.user.username),
                     sendername="Planet PostgreSQL",
                     receivername="Planet PostgreSQL Moderators",

hamnadmin/hamnadmin/register/templates/edit.html
{% extends "base.tmpl" %}
{% block content %}
    <div class="col-md-12">

    {% if new %}
        <h1>Add blog</h1>
    {% else %}
        <h1>Edit blog</h1>
    {% endif %}

        {% if not new %}
            <h3>Status</h3>
            <p>
                {% if blog.approved %}
                    This blog is currently <span class="badge badge-success">approved</span>.
                    {% if blog.recent_failures %}
                        {% if blog.recent_failures <= 5 %}
                            This blog has generated <span class="badge badge-warning">sporadic errors</span> in the past 24 hours. See
                            the <a href="#log">log</a> below for details.
                        {% else %}
                            This blog has generated <span class="badge badge-danger">multiple failures</span> in the past 24 hours. See
                            the <a href="#log">log</a> below for details.
                        {% endif %}
                    {% else %}{#recent_failures#}
                        The blog last posted an entry at <span class="badge badge-info">{{ blog.latestentry.dat|date:"Y-m-d H:i:s" }}</span>.
                    {% endif %}

                {% else %}
                    This blog is currently <span class="badge badge-warning">not approved</span>.</p>
                    {% if blog.has_entries %}
                        The blog is currently waiting for moderator approval.
                    {% else %}
                        The blog has not yet received any posts. As soon as the first post is syndicated, the blog will be
                        automatically submitted for approval.
                    {% endif %}{#has_entries#}
                {% endif %}{#approved#}
            </p>
        {% endif %}{#not new#}

    {% if user.is_superuser and not new %}
        <h3>Moderator Notes</h3>
        {% if notes %}
        <table class="table table-condensed table-striped">
            <tr>
                <th style="width: 60%">Note</th>
                <th style="width: 20%">Moderator</th>
                <th style="width: 20%">Date/Time</th>
            </tr>
            {% for n in notes %}
                <tr>
                    <td>{{ n.note }}</td>
                    <td>{{ n.user }}</td>
                    <td>{{ n.ts|date:"Y-m-d H:i:s" }}</td>
                </tr>
            {% endfor %}
        </table>
        {% endif %}

        <form method="post" action=".">{% csrf_token %}
            <div class="form-row align-items-center">
                <div class="col-auto" style="width: 60%">
                    <label for="id_note" class="sr-only">New note</label>
                    <input type="text" name="note" class="form-control mb-2" id="id_note">
                </div>
                <div class="col-auto" style="width: 40%">
                    <button type="submit" class="btn btn-primary mb-2">Add Note</button>
                </div>
            </div>
        </form>
    {% endif %}

    {% if messages %}
        <h3>Results</h3>
        <div class="alert alert-info">
            {% for m in messages %}
                {{ m }}<br/>
            {% endfor %}
        </div>
    {% endif %}

    {% if posts %}
        <h3>Posts</h3>
        <p>The latest posts received from this blog are:</p>
        <table class="table table-condensed table-striped">
            <tr>
                <th>Date</th>
                <th>Title</th>
                <th>Show/Hide</th>
            </tr>
            {% for p in posts %}
                <tr>
                    <td>{{ p.dat|date:"Y-m-d H:i:s" }}</td>
                    <td><a href="{{ p.link }}">{{ p.title }}</a></td>
                    <td>
                        {% if p.hidden %}
                            <a class="btn btn-primary btn-sm" href="/register/blogposts/{{ blog.id }}/unhide/{{ p.id }}/">Unhide</a>
                        {% else %}
                            <a class="btn btn-primary btn-sm" href="/register/blogposts/{{ blog.id }}/hide/{{ p.id }}/">Hide</a>
                        {% endif %}
                        <a class="btn btn-warning btn-sm" href="javascript:confirmDelete({{ blog.id }},{{ p.id }})">Delete/reload</a>
                    </td>
                </tr>
            {% endfor %}
        </table>
        <a class="btn btn-primary btn-sm" href="/register/">Return</a>
    {% endif %}

{% if new %}
    <h3>Register</h3>
{%  else %}
    <h3>Edit</h3>
{% endif %}

    {% if form.errors %}
        <div class="alert alert-danger">Please correct the errors below, and re-submit the form.</div>
    {% endif %}

    {% if form.non_field_errors %}
        {% for e in form.non_field_errors %}
            <div class="alert alert-danger">{{ e }}</div>
        {% endfor %}
    {% endif %}

    <form method="post" action="." class="form-horizontal">{% csrf_token %}
        {% for field in form %}
            <div class="form-group{% if field.errors %} has-error{% endif %}">
                <label for="{{ field.id }}" class="col-sm-2">{{ field.label }}</label>
                <div class="col-sm-10">
                    <div class="controls">
                        {{ field }}
                        <span class="help-block">{{ field.help_text }}</span>
                        {% if field.errors %}
                            <span class="help-block">{{ field.errors }}</span>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
        <br />
        <input class="btn btn-primary btn-sm" type="submit" value="Save">
        <a class="btn btn-secondary btn-sm" href="/register/">Cancel</a>
        <a class="btn btn-danger btn-sm" href="javascript:confirmDeleteBlog({{ blog.id }})">Delete</a>
        {% if blog.approved and blog.has_entries %}
            <a class="btn btn-primary btn-sm" href="javascript:confirmArchiveBlog({{ blog.id }})">Archive</a>
        {% endif %}
    </form>

    {% if not new %}
        <a name="log"></a>
        <h3>Log</h3>
        {% if blog.lastsuccess %}
            <p>
                The last successful fetch of this feed was <em>{{ blog.lastsuccess|date:"Y-m-d H:i:s" }}.</em>
            </p>
        {% endif %}
        <table class="table table-condensed table-striped">
            <tr>
                <th>Time</th>
                <th>Success</th>
                <th>Text</th>
            </tr>
            {% for l in log %}
                <tr>
                    <td>{{ l.ts|date:"Y-m-d H:i:s" }}</td>
                    <td>
                        {% if l.success %}<span class="badge badge-success">Success</span>
                        {% elif l.ts < blog.lastsuccess %}<span class="badge badge-warning" title="A successful fetch has been completed after this failure occurred">Past failure</span>
                        {% else %}<span class="badge badge-danger">Failure</span>{% endif %}
                    </td>
                    <td>{{ l.info }}</td>
                </tr>
            {% endfor %}
        </table>
    {% endif %}{#not new#}

{% endblock %}
{% block extrahead %}
    <script type="text/javascript">
        function confirmDelete(blogid, postid) {
            if (window.confirm("Are you sure you want to delete the post?\n\nThe post will automatically re-appear on the next crawl if it's still in the feed. If you don't want that to happen, hide the post instead!\n\nAre you sure?")) {
                document.location.href='/register/blogposts/' + blogid + '/delete/' + postid + '/';
            }
        }

        function confirmDeleteBlog(blogid) {
            if(window.confirm("Are you sure you want to delete this blog?\n\nAll entries in the blog as well as all history will be deleted.\n\nNormally, you should Archive the blog instead of delete it if it has any posts in it, since those posts will then not be deleted.\n\nAre you sure you want to delete (and not archive) this blog?")) {
                document.location.href='/register/delete/' + blogid + '/';
            }
        }

        function confirmArchiveBlog(blogid) {
            if(window.confirm("Are you sure you want to archive this blog?\n\nArchiving means that Planet PostgreSQL will no longer attempt to download any entries from the blog (so you will not get any error messages), but it remains in the history of Planet for future reference.\n\nAre you sure?")) {
                document.location.href='/register/archive/' + blogid + '/';
            }
        }
    </script>
    </div>

{% endblock %}

hamnadmin/hamnadmin/register/templates/moderate.html
{% extends "base.tmpl" %}
{% block content %}

    <div class="col-md-12">
        {% if messages %}
            <h3>Results</h3>
            <div class="alert alert-info">
                {% for m in messages %}
                    {{ m }}<br/>
                {% endfor %}
            </div>
        {% endif %}

        {% if user.is_superuser %}
            <h1>Superuser options</h1>
            <p>As a superuser you have additional options available:</p>
            <a class="btn btn-primary btn-sm" href="/register/?admin=1">View all blogs</a>
            <a class="btn btn-primary btn-sm" href="/register/">View your blogs</a>
            <a class="btn btn-warning btn-sm" href="/register/admin/">Django Admin</a>
        {% endif %}

        <h1>Blog moderation</h1>

        <p>The following blogs require moderator action:</p>
        {% for blog in blogs %}
            <div class="panel panel-info border px-3 pb-3">
                <div class="panel-heading"><h2>{{ blog.name|default:blog.feedurl }}</h2></div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-sm-1"><strong>User</strong></div>
                        <div class="col-sm-10"><strong>Username:</strong> {{ blog.user }}<br/><strong>Email:</strong> {{ blog.user.email }}<br/><strong>Twitter:</strong> {{ blog.twitteruser }}<br/><strong>Team:</strong> {{ blog.team.name }}<br/>&nbsp;</div>
                    </div>
                    <div class="row">
                        <div class="col-sm-1"><strong>URLs</strong></div>
                        <div class="col-sm-10">
                            <strong>Feed URL:</strong> <a href="{{ blog.feedurl }}">{{blog.feedurl}}</a><br/>
                            <strong>Blog URL:</strong> {% if blog.blogurl %}<a href="{{ blog.blogurl }}">{{ blog.blogurl }}</a>{% else %}Blog not syndicated yet, so no URL available.{% endif %}
                            {% if blog.authorfilter %}<br/>Author filter: {{ blog.authorfilter }}{% endif %}<br/>&nbsp;
                        </div>
                    </div>

                    {% if user.is_superuser and blog.moderatornotes_set.all %}

                    <div class="row">
                        <div class="col-sm-1"><strong>Moderator notes</strong></div>
                        <div class="col-sm-10">
                            <table class="table table-condensed table-striped table-bordered">
                                <tr><th>Notes</th><th>Moderator</th><th>Date/Time</th></tr>
                                {% for n in blog.moderatornotes_set.all %}
                                    <tr>
                                        <td style="width: 60%">{{ n.note }}</td>
                                        <td style="width: 20%">{{ n.user }}</td>
                                        <td style="width: 20%">{{ n.ts|date:"Y-m-d H:i:s" }}</td>
                                    </tr>
                                {% endfor %}
                            </table>
                        </div>
                    </div>
                    {% endif %}

                    <div class="row">
                        <div class="col-sm-1"><strong>Posts</strong></div>
                        <div class="col-sm-10">
                            {% if blog.recent_entries %}
                                <table class="table table-condensed table-striped table-bordered">
                                    <tr><th>Time</th><th>Title</th></tr>
                                    {% for p in blog.recent_entries %}
                                        <tr>
                                            <td>{{ p.dat|date:"Y-m-d H:i:s" }}</td>
                                            <td><a href="{{ p.link }}">{{ p.title }}</a></td>
                                        </tr>
                                    {% endfor %}
                                </table>
                            {% else %}
                                No entries have been syndicated from this blog yet.
                            {% endif %}
                            <em>Last successful HTTP fetch dated: {{ blog.lastget|date:"Y-m-d H:i:s" }} (fetch date or Last-Modified HTTP header).<br/>&nbsp;</em>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            {% if blog.recent_entries %}<a class="btn btn-sm btn-primary" href="javascript:confirmApprove('approve/{{blog.id}}/')">Approve</a>{% endif %}
                            <a class="btn btn-sm btn-primary" href="/register/edit/{{ blog.id }}/">Edit</a>
                            <a class="btn btn-sm btn-danger" href="reject/{{ blog.id }}/">Reject</a>
                            <a class="btn btn-sm btn-primary" href="/register/admin/register/blog/{{ blog.id }}/">Admin</a>
                        </div>
                    </div>
                </div>
            </div>
            <br/>
        {% endfor %}
    </div>

{% endblock %}

{% block extrahead %}

    <script type="text/javascript">
        function confirmApprove(url) {
            if (window.confirm('Are you sure you want to approve this blog?')) {
                document.location.href = url;
            }
        }
    </script>

{% endblock %}